version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: lexify-whatsapp-api
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - whatsapp-sessions:/app/sessions
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=1024
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

volumes:
  whatsapp-sessions:
    driver: local