version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: lexify-whatsapp-api
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - whatsapp-sessions:/app/sessions
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

volumes:
  whatsapp-sessions:
    driver: local